[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lumache"
authors = [{name = "Alla Fedorova", email = "fedorovaad1995@gmail.com"}]
dynamic = ["version", "description"]
